modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="sync"
version="0.2.0"
displayName="Sync"
authors="Pawjwp, Sumiku"
description='''One mind. Many bodies.'''
logoFile="assets/sync/icon.png"

# === DEPENDENCIES ===
[[dependencies."sync"]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies."sync"]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

